# Default values for algon.

replicaCount: 1

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: algon.local
      paths:
        - "/"
  tls: []

algorand:
  network: testnet
  config:
    algod:
      Version: 13
      AccountsRebuildSynchronousMode: 1
      AnnounceParticipationKey: true
      Archival: false
      BaseLoggerDebugLevel: 4
      BroadcastConnectionsLimit: -1
      CadaverSizeTarget: 1073741824
      CatchpointFileHistoryLength: 365
      CatchpointInterval: 10000
      CatchpointTracking: 0
      CatchupBlockDownloadRetryAttempts: 1000
      CatchupFailurePeerRefreshRate: 10
      CatchupGossipBlockFetchTimeoutSec: 4
      CatchupHTTPBlockFetchTimeoutSec: 4
      CatchupLedgerDownloadRetryAttempts: 50
      CatchupParallelBlocks: 16
      ConnectionsRateLimitingCount: 60
      ConnectionsRateLimitingWindowSeconds: 1
      DNSBootstrapID: "testnet.algorand.network"
      DNSSecurityFlags: 1
      DeadlockDetection: 0
      DisableOutgoingConnectionThrottling: false
      EnableAgreementReporting: false
      EnableAgreementTimeMetrics: false
      EnableAssembleStats: false
      EnableBlockService: false
      EnableDeveloperAPI: false
      EnableGossipBlockService: true
      EnableIncomingMessageFilter: false
      EnableLedgerService: false
      EnableMetricReporting: false
      EnableOutgoingNetworkMessageFiltering: true
      EnablePingHandler: true
      EnableProcessBlockStats: false
      EnableProfiler: false
      EnableRequestLogger: false
      EnableTopAccountsReporting: false
      EndpointAddress: "127.0.0.1:0"
      FallbackDNSResolverAddress: ""
      ForceRelayMessages: false
      GossipFanout: 4
      IncomingConnectionsLimit: 10000
      IncomingMessageFilterBucketCount: 5
      IncomingMessageFilterBucketSize: 512
      IsIndexerActive: false
      LedgerSynchronousMode: 2
      LogArchiveMaxAge: ""
      LogArchiveName: "node.archive.log"
      LogSizeLimit: 1073741824
      MaxCatchpointDownloadDuration: 7200000000000
      MaxConnectionsPerIP: 30
      MinCatchpointFileDownloadBytesPerSecond: 20480
      NetAddress: ""
      NetworkMessageTraceServer: ""
      NetworkProtocolVersion: ""
      NodeExporterListenAddress: ":9200"
      NodeExporterPath: "./node_exporter"
      OptimizeAccountsDatabaseOnStartup: false
      OutgoingMessageFilterBucketCount: 3
      OutgoingMessageFilterBucketSize: 128
      PeerConnectionsUpdateInterval: 3600
      PeerPingPeriodSeconds: 0
      PriorityPeers: {}
      PublicAddress: ""
      ReconnectTime: 60000000000
      ReservedFDs: 256
      RestReadTimeoutSeconds: 15
      RestWriteTimeoutSeconds: 120
      RunHosted: false
      SuggestedFeeBlockHistory: 3
      SuggestedFeeSlidingWindowSize: 50
      TLSCertFile: ""
      TLSKeyFile: ""
      TelemetryToLog: true
      TxPoolExponentialIncreaseFactor: 2
      TxPoolSize: 15000
      TxSyncIntervalSeconds: 60
      TxSyncServeResponseSize: 1000000
      TxSyncTimeoutSeconds: 30
      UseXForwardedForAddressField: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

image:
  repository: randmeister/algon
  tag: stable
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # privileged: false
  # readOnlyRootFilesystem: true
  # allowPrivilegeEscalation: false
  # runAsUser: 10001
  # runAsGroup: 10001
  # capabilities:
  #   drop:
  #   - ALL
  # seccompProfile:
  #   type: RuntimeDefault

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

storage:
  size: 5Gi
